version: "2"
services:
  flask:
    build: .
    image: flask
    command: uwsgi --http-socket 0.0.0.0:5000 --wsgi-file Server.py --callable app
    labels:
      - "traefik.enable=true"
      - "traefik.backend=flask"
      - "traefik.frontend.rule=Host:timmy.rent
  traefik:
    image: traefik:v1.7.16
    labels:
      - "traefik.domain=timmy.rent"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./traefik/acme:/etc/traefik/acme
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
